### ISSUE TITLE
Some ideas to improve the C# SDK

### ISSUE THREAD

**Issue by tylerlong** [tylerlong/ringcentral-csharp#1]
#### JS

``` javascript
var RingCentral = require('ringcentral');
var rc = new RingCentral({ 
    server: 'https://platform.devtest.ringcentral.com', 
    appKey: 'app key',
    appSecret: 'app secret'
});
var platform = rc.platform();

platform
  .login({
      username: config.username,
      extension: '',
      password: config.password
  })
  .then(function(response) {
    platform.post('/account/~/extension/~/sms', jsonText)
      .then(function() { console.log('sms sent'); })
      .catch(errorHandler);
  })
  .catch(errorHandler);
```
#### CSharp

``` csharp
var rc = new RingCentral.SDK.SDK(
    "app key",
    "app secret",
    "https://platform.devtest.ringcentral.com", // API EndPoint.
    "app name",
    "app version"
)
var platform = rc.GetPlatform();

platform.Authorize(username, extension, password, true);

var request = new RingCentral.SDK.Http.Request("/restapi/v1.0/account/~/extension/~/sms", jsonText);
var response = platform.Post(request);
MessageBox.Show("sms sent, response status: " + response.GetStatus(), "Try RingCentral");
```
## namespace

For JS, the path to `platform` is `ringcentral -> platform`.

For C#, the path to `platform` is `RingCentral -> SDK -> SDK -> platform`.
#### Conclusion / Solution

C#'s namespace is too long, `... -> SDK -> SDK -> ...` is not necessary.

Shorten the namespace.
## naming

`API EndPoint` in C# is `server` in JS, which is very confusing.
#### Conclusion / Solution

Change C# code and rename `API EndPoint` to `server`.
## Parameters' order

When Creating a RingCentral instance, JS takes an object as parameter. We all know that object's attributes have no order. But in the sample code from readme, there is order: server, appKey, appSecret...etc.

The corresponding C# code, the parameters' order is: appKey, appSecret, apiEndpoint...etc.

The orders are different.
#### Conclusion / Solution

Change C# code and adjust parameters' order.
## some parameters should be optional

When creating a RingCentral instance, C# code requires `appName` and `appVersion`. JS code doesn't require these because JS is not static compiled language.

I think these two parameters (`appName` and `appVersion`) should be optional. Because in JS it is optional. And server side can easily get app's information with `appKey` and `appSecret`. It doesn't make much sense to require client code to provide such information.
#### Conclusion / Solution

Change C# code and make `appName` and `appVersion` optional.
## API url prefix

JS: `/account/~/extension/~/sms`
C#: `/restapi/v1.0/account/~/extension/~/sms`

In C#, programmer has to prefix the url with `/restapi/v1.0`.
#### Conclusion / Solution

Change C# code and auto prefix `/resetapi/v1.0` if programmer forgot to do so.

**Comment by tylerlong** [comment]
Response from @grokify:

> 
> please make reference to the SDK Reference. The JS SDK is one implementation of the SDK Reference as is the JS. Sometimes, a SDK (JS, PHP, etc.) could be ahead of the SDK Reference, but be sure to check it.
> 
> (1) Namespace:
> 
> The existing C# syntax `RingCentral.SDK.SDK` actually mimics our old SDK Reference.
> 
> The path should be shorted to ideally mimic our SDK Reference.
> 
> (2) Naming:
> 
> Okay to rename `apiEndPoint` to `server` per SDK Reference.
> 
> (3) Parameters' order
> 
> Do not change the order here without more discussing. The starting order (`appKey`, `appSecret`, `server`,...) follow the SDK Reference which does have an order:
> 
> https://github.com/ringcentral/sdk-reference/blob/master/SDK.ts#L17
> 
> The JS SDK README.md should be updated to reflect the SDK Reference
> 
> (4) Optional Parameters
> 
> Let's keep these parameters mandatory now. They are used in the USER-AGENT HTTP header so it's useful to have for when we start analyzing the SDK USER-AGENTs.
> 
> (5) API URL Prefix
> 
> Here, I think we should discuss changing the JS SDK here since the JS URL is inaccurate:
> ​Inaccurate: JS: `/account/~/extension/~/sms`
> ​Accurate: JS: `account/~/extension/~/sms`
> Accurate: C#: `/restapi/v1.0/account/~/extension/~/sms`
> Let's discuss with Kirill whether we can use:
> `account/~/extension/~/sms`  for appending prefix.
> I feel that a `/restapi/v1.0/` should be prefixed if the URL provided doesn't have a leading `/` similar to directory paths.

**Comment by grokify** [comment]
The comments below refer to the RingCentral SDK Reference:
- https://github.com/ringcentral/sdk-reference

### namespace

Please update based on current SDK Reference. The C# SDK is currently based on an old version of the SDK Reference.

### naming

Please update `apiEndPoint` variable to `server` per SDK Reference:
- https://github.com/ringcentral/sdk-reference/blob/master/platform/Platform.ts#L15

### Parameters' order

The SDK Reference constructor uses [ `appKey`, `appSecret`, `server`, ... ]. Please maintain this order.

The JS SDK `README.md` should be updated to reflected the parameter ordering in the SDK Reference.

Please refer to SDK Reference:
- https://github.com/ringcentral/sdk-reference/blob/master/SDK.ts#L17
- https://github.com/ringcentral/sdk-reference/blob/master/platform/Platform.ts#L15

### some parameters should be optional

`appName` and `appVersion` should be optional per SDK Reference:
- https://github.com/ringcentral/sdk-reference/blob/master/SDK.ts#L20

**Comment by tylerlong** [comment]
Updated according to the SDK Reference.

For the namespace, I changed it to `namespace RingCentral`. The SDK Reference, corresponding code is `module RingCentral.ReferenceSDK`.   I don't think the C# code needs the `ReferenceSDK` part. Correct me if I am wrong and feel free to reopen this issue.

**Comment by tylerlong** [comment]
@grokify  there is something I cannot decide, please share with me your thoughts.

Let's take the `Platform` class for example.

According to SDK Reference, https://github.com/ringcentral/sdk-reference/blob/master/platform/Platform.ts#L1

module name is `module RingCentral.ReferenceSDK.platform`

Question: for C# code, what should be the namespace for the `Platform` class?

Several options:
1. `namespace RingCentral`
2. `namespace RingCentral.Platform`
3. `namespace RingCentral.SDK`
4. `namespace RingCentral.SDK.Platform`
5. `namespace RingCentral.CSharpSDK`
6. `namespace RingCentral.CSharpSDK.Platform`
7. ...

Originally it was `namespace RingCentral.SDK`, I changed it to `namespace RingCentral`. But maybe `namespace RingCentral.CSharpSDK.Platform` is the best match for SDK Reference?

**Update** I also read the code of the JS SDK: https://github.com/ringcentral/ringcentral-js/blob/master/src/platform/Platform.js   I think if we follow JS SDK' example, `Platform` class's namespace should be `namespace RingCentral.Platform`. And the full path to the class is `RingCentral.Platform.Platform`.  And yes I know there are two `Platform`s in the path. And it is exactly what the SDK Reference tells us to do.
