### ISSUE TITLE
`loggedIn` vs `IsAuthorized `

### ISSUE THREAD

**Issue by tylerlong** [tylerlong/ringcentral-csharp#2]
There is a method in the class `Platform` named `IsAuthorized`.

But according to the SDK Reference, the name should be `loggedIn`.

**Comment by grokify** [comment]
The C# SDK is currently implemented against an old version of the SDK Reference so there are some discrepancies. The methods and class names should be updated to reflect the latest SDK Reference. The method above is one area that needs to be updated.

**Comment by tylerlong** [comment]
Updated according to the SDK Reference.
